export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const INCREMENT_COUNTER_ADD = 'INCREMENT_COUNTER_ADD'
export const UPDATE_URL = 'UPDATE_URL'
